export const PERMISSIONS = [
  'be_enrolled',
  'be_managed',
  'be_selected',
  'give_exit_authorization',
  'login',
  'manage_activities',
  'manage_attendances',
  'manage_classes',
  'manage_enrollments',
  'manage_events',
  'manage_personal_info',
  'manage_roles',
  'manage_self_child_users',
  'manage_teams',
  'manage_users',
  'manage_weeks',
  'register',
  'register_child_users',
  'see_activities',
  'see_personal_info',
  'see_classes',
  'see_users',
] as const;
export type Permission = (typeof PERMISSIONS)[number];
