[server]
port = 3000
host = '0.0.0.0'
routes_prefix = '/api'
use_https = false
domain = 'localhost'
frontend_port = 4200
music_folder = '../public/music'

[https]
# if use_https is disabled the following settings are ignored
# the paths are relative to the project root
cert = 'ssl/cert.pem'
key = 'ssl/key.pem'

[logs]
log_level = 'debug'
log_folder = 'logs'

[database]
host = 'localhost'
port = 3306
user = 'root'
password = ''
database = 'oratorio'
wait_for_connections = true
connection_limit = 10
queue_limit = 3
